## Learn Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

NumPy (Numerical Python) is a fundamental Python library for numerical computing. It provides support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to perform operations on these arrays efficiently. NumPy is widely used in data analysis, machine learning, and scientific computing due to its speed and versatility.

## Create & Read

#### 1D Array

In [4]:
# Create one dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
# Get the type of the array
type(arr1)

numpy.ndarray

In [6]:
# See the shape of the array
arr1.shape

(5,)

In [7]:
# Data types of the elements
arr1.dtype

dtype('int32')

In [8]:
# Check array type
arr1.ndim

1

In [10]:
# Array size
arr1.size

5

#### 2D Array

In [12]:
arr2 = np.array([[1, 4, 6], [25, 78, 90]])
arr2

array([[ 1,  4,  6],
       [25, 78, 90]])

In [13]:
# Check the dimension
arr2.ndim

2

In [14]:
# Check the shape
arr2.shape

(2, 3)

In [16]:
# Check the size
# that's number of element in an array
arr2.size

6

#### 3D Array

A 3D array in NumPy is a collection of 2D arrays (matrices), organized along a third dimension. It is essentially a stack of arrays, allowing you to store and manipulate data in three dimensions (e.g., height, rows, and columns).

In [18]:
import numpy as np

# Create a 3D array with shape (2, 3, 4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

array_3d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
array_3d.shape

(2, 3, 4)

*Shape:* (2, 3, 4) — 2 matrices, each with 3 rows and 4 columns.

#### Access Elements in 3D Array

In [20]:
print(array_3d[0, 1, 2])  # Access element in 1st matrix, 2nd row, 3rd column


7


In NumPy, all 2D arrays (or slices) within a 3D array must have the same size. This is because NumPy arrays are designed to be efficient and require a fixed shape for each dimension.

For example, a 3D array with shape (2, 3, 4) has:

 - 2 matrices (first dimension),
 - each with 3 rows (second dimension),
 - and 4 columns (third dimension).

Each 2D array (matrix) must have exactly 3 × 4 elements.

If you try to create a 3D array with 2D arrays of varying sizes, NumPy will not create a true 3D array. Instead, it will create an array of objects (dtype=object), which is less efficient and does not support typical array operations like slicing or broadcasting.

#### Create random arrays

In [21]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.40272864, 0.88046706, 0.45497885],
        [0.2815239 , 0.28912258, 0.19991599]],

       [[0.26932656, 0.17820489, 0.37304879],
        [0.87179773, 0.06150348, 0.17029643]],

       [[0.91752732, 0.62248231, 0.13075802],
        [0.32448013, 0.16300391, 0.75602356]]])

In [22]:
randomArr.dtype

dtype('float64')

In [24]:
# Create array with zeros
zeros = np.zeros((3, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
# Check the dimension
zeros.ndim

3

In [29]:
# Replace the zeros with actual numbers
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

#### Slicing 3D Array

In [30]:
arr3d = np.array([[[74, 31,  5, 29],
                    [84, 77, 66, 98],
                    [62, 76, 54, 80]],
            
                   [[32, 17,  8, 91],
                    [81, 37, 87, 37],
                    [18, 27, 13, 55]],
            
                   [[67, 70, 71, 98],
                    [86, 67, 22, 25],
                    [62, 75, 96, 15]],
            
                   [[58, 95, 79, 79],
                    [82, 96,  6,  7],
                    [56, 59, 37, 54]]])

arr3d


array([[[74, 31,  5, 29],
        [84, 77, 66, 98],
        [62, 76, 54, 80]],

       [[32, 17,  8, 91],
        [81, 37, 87, 37],
        [18, 27, 13, 55]],

       [[67, 70, 71, 98],
        [86, 67, 22, 25],
        [62, 75, 96, 15]],

       [[58, 95, 79, 79],
        [82, 96,  6,  7],
        [56, 59, 37, 54]]])

In [31]:
# Access first index of the 3D Array
arr3d[0]

array([[74, 31,  5, 29],
       [84, 77, 66, 98],
       [62, 76, 54, 80]])

The first 2D array inside the 3D array

In [32]:
# Access the first index of the first 2D array inside the 3D array

arr3d[0][0]

array([74, 31,  5, 29])

In [33]:
# slice 0 to 1. 1 inclueded
arr3d[0:2]

array([[[74, 31,  5, 29],
        [84, 77, 66, 98],
        [62, 76, 54, 80]],

       [[32, 17,  8, 91],
        [81, 37, 87, 37],
        [18, 27, 13, 55]]])

In [34]:
# Accessing single element
arr3d[1][0][1]

17

In [35]:
# You can perform the same operation above another way:
arr3d[1, 0, 1]

17

#### Update & Delete

In [40]:
ar_1 = np.array([[[9, 5],
                  [7, 8],
                  [1, 2]],
                
                 [[2, 1],
                  [6, 8],
                  [1, 1]]])

ar_2 = np.array([[[2, 2],
                  [5, 3],
                  [7, 6]],
                
                 [[7, 4],
                  [8, 7],
                  [8, 3]]])

In [41]:
ar_1

array([[[9, 5],
        [7, 8],
        [1, 2]],

       [[2, 1],
        [6, 8],
        [1, 1]]])

In [42]:
ar_2

array([[[2, 2],
        [5, 3],
        [7, 6]],

       [[7, 4],
        [8, 7],
        [8, 3]]])

##### Basic Arithmetics Operations

In [43]:
# Array additiom
np.add(ar_1, ar_2)

array([[[11,  7],
        [12, 11],
        [ 8,  8]],

       [[ 9,  5],
        [14, 15],
        [ 9,  4]]])

In [45]:
# Array substraction
np.subtract(ar_1, ar_2)

array([[[ 7,  3],
        [ 2,  5],
        [-6, -4]],

       [[-5, -3],
        [-2,  1],
        [-7, -2]]])

In [46]:
# Array division
np.divide(ar_1, ar_2)


array([[[4.5       , 2.5       ],
        [1.4       , 2.66666667],
        [0.14285714, 0.33333333]],

       [[0.28571429, 0.25      ],
        [0.75      , 1.14285714],
        [0.125     , 0.33333333]]])

In [47]:
# Array Multiplication
np.multiply(ar_1, ar_2)

array([[[18, 10],
        [35, 24],
        [ 7, 12]],

       [[14,  4],
        [48, 56],
        [ 8,  3]]])

### Statistical Operations

Common NumPy statistical operations using a sample array:

In [51]:
example_array = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
example_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
example_array.shape

(3, 3)

#### Mean


In [53]:
np.mean(example_array)


5.0

The average value of all elements in the array.



#### Median

In [54]:
np.median(example_array)


5.0

The middle value when the elements are sorted.



#### Standard Deviation


In [56]:
np.std(example_array)


2.581988897471611

Measures how spread out the numbers are from the mean.

 #### Maximum and Minimum

In [59]:
np.max(example_array), np.min(example_array)


(9, 1)

#### Sum

In [60]:
np.sum(example_array)


45

The total of all elements.

#### Argmax and Argmin

In [61]:
np.argmax(example_array), np.argmin(example_array)


(8, 0)

##### Outputs:

 - Argmax: 8 (Index of the maximum value in the flattened   array.)

 - Argmin: 0 (Index of the minimum value in the flattened array.)

### Update Array values

In [62]:
arr3d

array([[[74, 31,  5, 29],
        [84, 77, 66, 98],
        [62, 76, 54, 80]],

       [[32, 17,  8, 91],
        [81, 37, 87, 37],
        [18, 27, 13, 55]],

       [[67, 70, 71, 98],
        [86, 67, 22, 25],
        [62, 75, 96, 15]],

       [[58, 95, 79, 79],
        [82, 96,  6,  7],
        [56, 59, 37, 54]]])

In [63]:
arr3d[0][0][3] = 2000

In [64]:
arr3d

array([[[  74,   31,    5, 2000],
        [  84,   77,   66,   98],
        [  62,   76,   54,   80]],

       [[  32,   17,    8,   91],
        [  81,   37,   87,   37],
        [  18,   27,   13,   55]],

       [[  67,   70,   71,   98],
        [  86,   67,   22,   25],
        [  62,   75,   96,   15]],

       [[  58,   95,   79,   79],
        [  82,   96,    6,    7],
        [  56,   59,   37,   54]]])

### Sorting Array

In [66]:
arr3d.sort()
arr3d

array([[[   5,   31,   74, 2000],
        [  66,   77,   84,   98],
        [  54,   62,   76,   80]],

       [[   8,   17,   32,   91],
        [  37,   37,   81,   87],
        [  13,   18,   27,   55]],

       [[  67,   70,   71,   98],
        [  22,   25,   67,   86],
        [  15,   62,   75,   96]],

       [[  58,   79,   79,   95],
        [   6,    7,   82,   96],
        [  37,   54,   56,   59]]])

### Reshaping Array

In [67]:
arr3d.shape

(4, 3, 4)

In [68]:
arr3d_newshape = arr3d.reshape((3, 4, 4))
arr3d_newshape

array([[[   5,   31,   74, 2000],
        [  66,   77,   84,   98],
        [  54,   62,   76,   80],
        [   8,   17,   32,   91]],

       [[  37,   37,   81,   87],
        [  13,   18,   27,   55],
        [  67,   70,   71,   98],
        [  22,   25,   67,   86]],

       [[  15,   62,   75,   96],
        [  58,   79,   79,   95],
        [   6,    7,   82,   96],
        [  37,   54,   56,   59]]])

### Appending and inserting

#### Appending

In [72]:
zeros = np.zeros((3, 2, 3))
ones = np.ones((3, 2, 3))


In [73]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [76]:
appendarr = np.append(zeros, ones, axis=0)
# axis 0 = row, axis 1 = column
appendarr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### Inserting

In [77]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
insertedarray = np.insert(zeros, 1, ones, axis=0)
insertedarray

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])